# Workflow file of GitHub Actions

name: build

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os: [ js ]
        arch: [ wasm, was7 ]
        go: [ 1.13 ]


    steps:
      - name: Checkout scm
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: 'Test on [js] arch [wasm]'
        if: ${{ matrix.os == 'js' && contains('wasm', matrix.arch) }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          GOARM: ${{ matrix.arch[3] }}
        run: |
          echo $GOARM
          echo ===
          echo $GOROOT
          PATH=$PATH:`go env|grep GOROOT| awk -F '=' '{print $2}'|awk -F '"' '{print $2}'`/misc/wasm
          echo $PATH
          a=a:`go env|grep GOROOT| awk -F '=' '{print $2}'|awk -F '"' '{print $2}'`/misc/wasm
          echo a


