# Workflow file of GitHub Actions

name: build

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os: [ js ]
        arch: [ wasm, was7 ]
        go: [ 1.13 ]


    steps:
      - name: Checkout scm
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: 'Test on [js] arch [wasm]'
        if: ${{ matrix.os == 'js' && contains('wasm', matrix.arch) }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          GOARM: ${{ matrix.arch[3] }}
        run: |
          sudo apt-get -y install qemu-user-static
          sudo wget -o /usr/bin/qemu-loongarch64-static https://github.com/loongson/build-tools/releases/download/2022.09.06/qemu-loongarch64
          ls -a -l /usr/bin/qemu*
          sudo chmod +x /usr/bin/qemu-loongarch64-static
          ls -a -l /usr/bin/qemu*
          ls /proc/sys/fs/binfmt_misc -a -l
          /usr/bin/qemu-loongarch64-static echo 1

