# Workflow file of GitHub Actions

name: build

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os: [ linux ]
        arch: [ loong64 ]
        go: [ 1.19 ]


    steps:
      - name: Checkout scm
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: 'Test on loong64'
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          sudo apt-get -y install qemu-user-static
          echo ==========
          sudo wget -O /usr/bin/qemu-loongarch64-static https://github.com/loongson/build-tools/releases/download/2022.09.06/qemu-loongarch64
          sudo chmod +x /usr/bin/qemu-loongarch64-static
          sudo ln -s /usr/bin/qemu-loongarch64-static /usr/libexec/qemu-binfmt/loongarch64-binfmt-P
          echo ==========
          ls -a -l /proc/sys/fs/binfmt_misc
          sudo chmod 200 /proc/sys/fs/binfmt_misc/register
          echo ==========
          ls -a -l /proc/sys/fs/binfmt_misc
          sudo sh -c 'echo ":qemu-loongarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x02\x01:\xff\xff\xff\xff\xff\xff\xff\xfc\x00\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/libexec/qemu-binfmt/loongarch64-binfmt-P:" > /proc/sys/fs/binfmt_misc/register'
  
          echo ==========
          go test -v ./...
